/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-19 04:35:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1755577915330L));
    _jspx_dependants.put("jar:file:/C:/academi/JSP-Servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/secTeamProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>이벤트</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-color: #000;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 상단 배너 느낌 */\r\n");
      out.write(".event-banner {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	background-image: url('images/event-banner.jpg');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	text-shadow: 2px 2px 6px rgba(0, 0, 0, 0.7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	padding: 40px 20px;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	max-width: 1300px; /* 컨테이너의 최대 너비를 3개 카드가 들어갈 크기로 제한 */\r\n");
      out.write("	margin: 0 auto; /* 컨테이너를 화면 중앙에 오도록 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card {\r\n");
      out.write("	background-color: #141414;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transition: transform 0.3s;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column; /* 세로 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card:hover {\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 180px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card-content {\r\n");
      out.write("	flex: 1; /* 남은 공간 채우기 */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	justify-content: space-between; /* 버튼을 아래쪽으로 */\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card-content h2 {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	color: #e0e0e0;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card-content p {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card-content button {\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	background: linear-gradient(45deg, #E74C3C, #FF6B9D);\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".event-card-content button:hover {\r\n");
      out.write("	background: linear-gradient(45deg, #FF6B9D, #E74C3C);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 1000px) {\r\n");
      out.write("	.event-card {\r\n");
      out.write("		width: 45%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 600px) {\r\n");
      out.write("	.event-card {\r\n");
      out.write("		width: 90%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"event-banner\">지금 진행 중인 이벤트</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"event-container\">\r\n");
      out.write("		<!-- 이벤트 카드 1 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/conjuring.jpg\" alt=\"이벤트1\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>신작 시사회 초대</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					회원 전용 신작 영화 시사회에 <br> 참여해보세요!\r\n");
      out.write("				</p>\r\n");
      out.write("				<button onclick=\"alert('참여 완료!')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이벤트 카드 2 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/popcorn.jpeg\" alt=\"이벤트2\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>함께하면 달콤한 시간</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					2인이상 예매 시 <br>팝콘 1+1 행사 진행중!\r\n");
      out.write("				</p>\r\n");
      out.write("				<!-- c영화 예매 시 팝콘 1+1 쿠폰을 드립니다. -->\r\n");
      out.write("				<button onclick=\"alert('참여 완료!')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이벤트 카드 3 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/coin.jpg\" alt=\"이벤트3\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>영화는 1번, 포인트는 2번!</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					특정 영화 예매 시<br>포인트를 두 배로 적립!\r\n");
      out.write("				</p>\r\n");
      out.write("				<button onclick=\"alert('참여 완료!')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이벤트 카드 4 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/f1.jpeg\" alt=\"이벤트4\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>영화 굿즈 증정</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					신작 영화 예매 하고<br>한정 굿즈도 받아가세요!\r\n");
      out.write("				</p>\r\n");
      out.write("				<button onclick=\"alert('참여 완료!')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이벤트 카드 5 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/couple.jpeg\" alt=\"이벤트5\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>커플 예매 이벤트</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					커플 예매 시 티켓<br>티켓비용 120% 적용!\r\n");
      out.write("				</p>\r\n");
      out.write("				<button onclick=\"alert('....?')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 이벤트 카드 6 -->\r\n");
      out.write("		<div class=\"event-card\">\r\n");
      out.write("			<img src=\"asset/images/sns.jpeg\" alt=\"이벤트6\">\r\n");
      out.write("			<div class=\"event-card-content\">\r\n");
      out.write("				<h2>SNS 인증 이벤트</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					영화 관람 후 SNS 인증 시<br>최대 5만원 스타벅스 쿠폰 증정!\r\n");
      out.write("				</p>\r\n");
      out.write("				<button onclick=\"alert('참여 완료!')\">참여하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
