/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-18 15:37:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LX-CINEMA í´ëì¤ ë¤ì´ì´ê·¸ë¨</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .diagram-container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0,0,0,0.1);\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            max-width: 1600px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .title {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            font-size: 2.5em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .subtitle {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .diagram {\r\n");
      out.write("            width: 1500px;\r\n");
      out.write("            height: 1000px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border: 2px solid #dee2e6;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .class-box {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 2px solid #333;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .class-box:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .class-name {\r\n");
      out.write("            background: #3498db;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 6px 6px 0 0;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .controller .class-name { background: #e74c3c; }\r\n");
      out.write("        .model .class-name { background: #27ae60; }\r\n");
      out.write("        .vo .class-name { background: #f39c12; }\r\n");
      out.write("        \r\n");
      out.write("        .attributes, .methods {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            border-top: 1px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .attributes {\r\n");
      out.write("            background: #ecf0f1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .methods {\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .attribute, .method {\r\n");
      out.write("            margin: 2px 0;\r\n");
      out.write("            font-family: 'Courier New', monospace;\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .private { color: #e74c3c; }\r\n");
      out.write("        .public { color: #27ae60; }\r\n");
      out.write("        .protected { color: #f39c12; }\r\n");
      out.write("        \r\n");
      out.write("        /* íì´í ì¤íì¼ */\r\n");
      out.write("        .arrow {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dependency-arrow {\r\n");
      out.write("            stroke: #3498db;\r\n");
      out.write("            stroke-width: 2;\r\n");
      out.write("            fill: none;\r\n");
      out.write("            stroke-dasharray: 5,5;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .association-arrow {\r\n");
      out.write("            stroke: #2c3e50;\r\n");
      out.write("            stroke-width: 2;\r\n");
      out.write("            fill: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .inheritance-arrow {\r\n");
      out.write("            stroke: #e74c3c;\r\n");
      out.write("            stroke-width: 2;\r\n");
      out.write("            fill: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .legend {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 2px solid #bdc3c7;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .legend-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .legend-color {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 15px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* ë ì´ì´ êµ¬ë¶ì  */\r\n");
      out.write("        .layer-divider {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            background: linear-gradient(to right, #bdc3c7, #ecf0f1, #bdc3c7);\r\n");
      out.write("            left: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .layer-label {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background: #34495e;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 5px 15px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 1200px) {\r\n");
      out.write("            .diagram {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 800px;\r\n");
      out.write("            }\r\n");
      out.write("            .class-box {\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("                min-width: 180px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"diagram-container\">\r\n");
      out.write("        <h1 class=\"title\">ð¬ LX-CINEMA ìì¤í</h1>\r\n");
      out.write("        <p class=\"subtitle\">UML í´ëì¤ ë¤ì´ì´ê·¸ë¨ - MVC ìí¤íì²</p>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"diagram\">\r\n");
      out.write("            <!-- ë²ë¡ -->\r\n");
      out.write("            <div class=\"legend\">\r\n");
      out.write("                <h4 style=\"margin: 0 0 10px 0; color: #2c3e50;\">ð Legend</h4>\r\n");
      out.write("                <div class=\"legend-item\">\r\n");
      out.write("                    <div class=\"legend-color\" style=\"background: #e74c3c;\"></div>\r\n");
      out.write("                    <span>Controller Layer</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"legend-item\">\r\n");
      out.write("                    <div class=\"legend-color\" style=\"background: #27ae60;\"></div>\r\n");
      out.write("                    <span>DAO Layer</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"legend-item\">\r\n");
      out.write("                    <div class=\"legend-color\" style=\"background: #f39c12;\"></div>\r\n");
      out.write("                    <span>VO Layer</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr style=\"margin: 10px 0;\">\r\n");
      out.write("                <div class=\"legend-item\">\r\n");
      out.write("                    <svg width=\"20\" height=\"15\">\r\n");
      out.write("                        <line x1=\"0\" y1=\"7\" x2=\"15\" y2=\"7\" stroke=\"#2c3e50\" stroke-width=\"2\"/>\r\n");
      out.write("                        <polygon points=\"15,7 10,4 10,10\" fill=\"#2c3e50\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <span style=\"margin-left: 5px;\">Association</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"legend-item\">\r\n");
      out.write("                    <svg width=\"20\" height=\"15\">\r\n");
      out.write("                        <line x1=\"0\" y1=\"7\" x2=\"15\" y2=\"7\" stroke=\"#3498db\" stroke-width=\"2\" stroke-dasharray=\"5,5\"/>\r\n");
      out.write("                        <polygon points=\"15,7 10,4 10,10\" fill=\"#3498db\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <span style=\"margin-left: 5px;\">Dependency</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ë ì´ì´ ë¼ë²¨ -->\r\n");
      out.write("            <div class=\"layer-label\" style=\"top: 20px; left: 20px;\">ð® Controller Layer</div>\r\n");
      out.write("            <div class=\"layer-label\" style=\"top: 350px; left: 20px;\">ð Model Layer (DAO)</div>\r\n");
      out.write("            <div class=\"layer-label\" style=\"top: 650px; left: 20px;\">ð·ï¸ Value Object Layer</div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ë ì´ì´ êµ¬ë¶ì  -->\r\n");
      out.write("            <div class=\"layer-divider\" style=\"top: 320px;\"></div>\r\n");
      out.write("            <div class=\"layer-divider\" style=\"top: 620px;\"></div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Controller Layer -->\r\n");
      out.write("            <!-- UserServlet -->\r\n");
      out.write("            <div class=\"class-box controller\" style=\"top: 60px; left: 50px;\">\r\n");
      out.write("                <div class=\"class-name\">ð UserServlet</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- serialVersionUID: long</div>\r\n");
      out.write("                    <div class=\"attribute private\">- udao: UserListDAO</div>\r\n");
      out.write("                    <div class=\"attribute private\">- mdao: MovieListDAO</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cdao: CinemaListDAO</div>\r\n");
      out.write("                    <div class=\"attribute private\">- rdao: ReserveListDAO</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method protected\">+ service(req, resp): void</div>\r\n");
      out.write("                    <div class=\"method private\">- makeUserFromReq(req): UserListVO</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- MovieServlet -->\r\n");
      out.write("            <div class=\"class-box controller\" style=\"top: 60px; left: 320px;\">\r\n");
      out.write("                <div class=\"class-name\">ð¬ MovieServlet</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- serialVersionUID: long</div>\r\n");
      out.write("                    <div class=\"attribute private\">- mdao: MovieListDAO</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cdao: CinemaListDAO</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method protected\">+ service(req, resp): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- CinemaServlet -->\r\n");
      out.write("            <div class=\"class-box controller\" style=\"top: 60px; left: 590px;\">\r\n");
      out.write("                <div class=\"class-name\">ð¢ CinemaServlet</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- serialVersionUID: long</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cdao: CinemaListDAO</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method protected\">+ service(req, resp): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ScheduleServlet -->\r\n");
      out.write("            <div class=\"class-box controller\" style=\"top: 60px; left: 860px;\">\r\n");
      out.write("                <div class=\"class-name\">ð ScheduleServlet</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- serialVersionUID: long</div>\r\n");
      out.write("                    <div class=\"attribute private\">- sdao: ScheduleListDAO</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method protected\">+ service(req, resp): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- DAO Layer -->\r\n");
      out.write("            <!-- UserListDAO -->\r\n");
      out.write("            <div class=\"class-box model\" style=\"top: 360px; left: 50px;\">\r\n");
      out.write("                <div class=\"class-name\">ð¤ UserListDAO</div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ login(id, pw): UserListVO</div>\r\n");
      out.write("                    <div class=\"method public\">+ register(user): boolean</div>\r\n");
      out.write("                    <div class=\"method public\">+ checkUser(userNo): UserListVO</div>\r\n");
      out.write("                    <div class=\"method public\">+ update(user): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ delete(userId): boolean</div>\r\n");
      out.write("                    <div class=\"method private\">- getConnection(): Connection</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- MovieListDAO -->\r\n");
      out.write("            <div class=\"class-box model\" style=\"top: 360px; left: 320px;\">\r\n");
      out.write("                <div class=\"class-name\">ð¥ MovieListDAO</div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getMovieList(): List&lt;MovieListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getTopMovies(): List&lt;MovieListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getGenreMovies(genre): List&lt;MovieListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieDetail(id): MovieListVO</div>\r\n");
      out.write("                    <div class=\"method public\">+ toggleLike(userNo, movieId): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ countLikes(movieId): int</div>\r\n");
      out.write("                    <div class=\"method private\">- getConnection(): Connection</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- CinemaListDAO -->\r\n");
      out.write("            <div class=\"class-box model\" style=\"top: 360px; left: 590px;\">\r\n");
      out.write("                <div class=\"class-name\">ð¬ CinemaListDAO</div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getCinemaList(): List&lt;CinemaListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getCinemasByLocation(location): List&lt;CinemaListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method private\">- getConnection(): Connection</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ScheduleListDAO -->\r\n");
      out.write("            <div class=\"class-box model\" style=\"top: 360px; left: 860px;\">\r\n");
      out.write("                <div class=\"class-name\">â° ScheduleListDAO</div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleDateList(movieId, cinemaId): List&lt;String&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleTimeList(movieId, cinemaId, date): List&lt;String&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleTimeWithId(movieId, cinemaId, date): List&lt;ScheduleListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleById(scheduleId): ScheduleListVO</div>\r\n");
      out.write("                    <div class=\"method private\">- getConnection(): Connection</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ReserveListDAO -->\r\n");
      out.write("            <div class=\"class-box model\" style=\"top: 360px; left: 1130px;\">\r\n");
      out.write("                <div class=\"class-name\">ð« ReserveListDAO</div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getReservationsByUserId(userId): List&lt;ReserveListVO&gt;</div>\r\n");
      out.write("                    <div class=\"method public\">+ createReservation(reservation): boolean</div>\r\n");
      out.write("                    <div class=\"method public\">+ deleteReservation(reservationId): boolean</div>\r\n");
      out.write("                    <div class=\"method private\">- getConnection(): Connection</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- VO Layer -->\r\n");
      out.write("            <!-- UserListVO -->\r\n");
      out.write("            <div class=\"class-box vo\" style=\"top: 660px; left: 50px;\">\r\n");
      out.write("                <div class=\"class-name\">ð UserListVO</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- userNo: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userId: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userName: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userAge: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userMobile: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userPassword: String</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getUserNo(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserNo(userNo): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserId(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserId(userId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserName(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserName(userName): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserAge(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserAge(userAge): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserMobile(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserMobile(userMobile): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserPassword(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserPassword(userPassword): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- MovieListVO -->\r\n");
      out.write("            <div class=\"class-box vo\" style=\"top: 660px; left: 320px;\">\r\n");
      out.write("                <div class=\"class-name\">ðï¸ MovieListVO</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- movieId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- movieTitle: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- moviePrice: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- movieTime: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- genre: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- poster: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- synopsis: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- likeCount: Integer</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getMovieId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieId(movieId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieTitle(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieTitle(movieTitle): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMoviePrice(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMoviePrice(moviePrice): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieTime(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieTime(movieTime): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getGenre(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setGenre(genre): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getPoster(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setPoster(poster): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getSynopsis(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setSynopsis(synopsis): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getLikeCount(): Integer</div>\r\n");
      out.write("                    <div class=\"method public\">+ setLikeCount(likeCount): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- CinemaListVO -->\r\n");
      out.write("            <div class=\"class-box vo\" style=\"top: 660px; left: 590px;\">\r\n");
      out.write("                <div class=\"class-name\">ðï¸ CinemaListVO</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- cinemaId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- name: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- location: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- address: String</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getCinemaId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setCinemaId(cinemaId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getName(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setName(name): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getLocation(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setLocation(location): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getAddress(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setAddress(address): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ScheduleListVO -->\r\n");
      out.write("            <div class=\"class-box vo\" style=\"top: 660px; left: 860px;\">\r\n");
      out.write("                <div class=\"class-name\">ð ScheduleListVO</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- scheduleId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- movieId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cinemaId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- showDate: Date</div>\r\n");
      out.write("                    <div class=\"attribute private\">- showTime: Time</div>\r\n");
      out.write("                    <div class=\"attribute private\">- movieTitle: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cinemaName: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- poster: String</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setScheduleId(scheduleId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieId(movieId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getCinemaId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setCinemaId(cinemaId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getShowDate(): Date</div>\r\n");
      out.write("                    <div class=\"method public\">+ setShowDate(showDate): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getShowTime(): Time</div>\r\n");
      out.write("                    <div class=\"method public\">+ setShowTime(showTime): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieTitle(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieTitle(movieTitle): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getCinemaName(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setCinemaName(cinemaName): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getPoster(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setPoster(poster): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ReserveListVO -->\r\n");
      out.write("            <div class=\"class-box vo\" style=\"top: 660px; left: 1130px;\">\r\n");
      out.write("                <div class=\"class-name\">ðï¸ ReserveListVO</div>\r\n");
      out.write("                <div class=\"attributes\">\r\n");
      out.write("                    <div class=\"attribute private\">- reservationId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- userId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- scheduleId: int</div>\r\n");
      out.write("                    <div class=\"attribute private\">- movieTitle: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- cinemaName: String</div>\r\n");
      out.write("                    <div class=\"attribute private\">- startTime: Timestamp</div>\r\n");
      out.write("                    <div class=\"attribute private\">- price: Integer</div>\r\n");
      out.write("                    <div class=\"attribute private\">- showDate: Date</div>\r\n");
      out.write("                    <div class=\"attribute private\">- showTime: Time</div>\r\n");
      out.write("                    <div class=\"attribute private\">- moviePoster: String</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"methods\">\r\n");
      out.write("                    <div class=\"method public\">+ getReservationId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setReservationId(reservationId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getUserId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setUserId(userId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getScheduleId(): int</div>\r\n");
      out.write("                    <div class=\"method public\">+ setScheduleId(scheduleId): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMovieTitle(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMovieTitle(movieTitle): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getCinemaName(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setCinemaName(cinemaName): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getStartTime(): Timestamp</div>\r\n");
      out.write("                    <div class=\"method public\">+ setStartTime(startTime): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getPrice(): Integer</div>\r\n");
      out.write("                    <div class=\"method public\">+ setPrice(price): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getShowDate(): Date</div>\r\n");
      out.write("                    <div class=\"method public\">+ setShowDate(showDate): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getShowTime(): Time</div>\r\n");
      out.write("                    <div class=\"method public\">+ setShowTime(showTime): void</div>\r\n");
      out.write("                    <div class=\"method public\">+ getMoviePoster(): String</div>\r\n");
      out.write("                    <div class=\"method public\">+ setMoviePoster(moviePoster): void</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- ê´ê³ì  ê·¸ë¦¬ê¸° (SVG) -->\r\n");
      out.write("            <svg style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none;\">\r\n");
      out.write("                <!-- UserServlet -> UserListDAO -->\r\n");
      out.write("                <line x1=\"150\" y1=\"260\" x2=\"150\" y2=\"360\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"150,360 145,350 155,350\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- UserServlet -> UserListVO -->\r\n");
      out.write("                <line x1=\"150\" y1=\"260\" x2=\"150\" y2=\"660\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"150,660 145,650 155,650\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- MovieServlet -> MovieListDAO -->\r\n");
      out.write("                <line x1=\"420\" y1=\"260\" x2=\"420\" y2=\"360\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"420,360 415,350 425,350\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- MovieServlet -> MovieListVO -->\r\n");
      out.write("                <line x1=\"420\" y1=\"260\" x2=\"420\" y2=\"660\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"420,660 415,650 425,650\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- CinemaServlet -> CinemaListDAO -->\r\n");
      out.write("                <line x1=\"690\" y1=\"260\" x2=\"690\" y2=\"360\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"690,360 685,350 695,350\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- CinemaServlet -> CinemaListVO -->\r\n");
      out.write("                <line x1=\"690\" y1=\"260\" x2=\"690\" y2=\"660\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"690,660 685,650 695,650\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- ScheduleServlet -> ScheduleListDAO -->\r\n");
      out.write("                <line x1=\"960\" y1=\"260\" x2=\"960\" y2=\"360\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"960,360 955,350 965,350\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- ScheduleServlet -> ScheduleListVO -->\r\n");
      out.write("                <line x1=\"960\" y1=\"260\" x2=\"960\" y2=\"660\" class=\"dependency-arrow\"/>\r\n");
      out.write("                <polygon points=\"960,660 955,650 965,650\" fill=\"#3498db\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- UserListDAO -> UserListVO -->\r\n");
      out.write("                <line x1=\"150\" y1=\"540\" x2=\"150\" y2=\"660\" class=\"association-arrow\"/>\r\n");
      out.write("                <polygon points=\"150,660 145,650 155,650\" fill=\"#2c3e50\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- MovieListDAO -> MovieListVO -->\r\n");
      out.write("                <line x1=\"420\" y1=\"540\" x2=\"420\" y2=\"660\" class=\"association-arrow\"/>\r\n");
      out.write("                <polygon points=\"420,660 415,650 425,650\" fill=\"#2c3e50\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- CinemaListDAO -> CinemaListVO -->\r\n");
      out.write("                <line x1=\"690\" y1=\"540\" x2=\"690\" y2=\"660\" class=\"association-arrow\"/>\r\n");
      out.write("                <polygon points=\"690,660 685,650 695,650\" fill=\"#2c3e50\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- ScheduleListDAO -> ScheduleListVO -->\r\n");
      out.write("                <line x1=\"960\" y1=\"540\" x2=\"960\" y2=\"660\" class=\"association-arrow\"/>\r\n");
      out.write("                <polygon points=\"960,660 955,650 965,650\" fill=\"#2c3e50\"/>\r\n");
      out.write("                \r\n");
      out.write("                <!-- ReserveListDAO -> ReserveListVO -->\r\n");
      out.write("                <line x1=\"1230\" y1=\"540\" x2=\"1230\" y2=\"660\" class=\"association-arrow\"/>\r\n");
      out.write("                <polygon points=\"1230,660 1225,650 1235,650\" fill=\"#2c3e50\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 30px; padding: 20px; background: #ecf0f1; border-radius: 10px;\">\r\n");
      out.write("            <h3 style=\"color: #2c3e50; margin-top: 0;\">ð í´ëì¤ ë¤ì´ì´ê·¸ë¨ ì¤ëª</h3>\r\n");
      out.write("            <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 20px; font-size: 14px;\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #e74c3c;\">ð® Controller Layer</h4>\r\n");
      out.write("                    <ul style=\"margin: 10px 0; padding-left: 20px;\">\r\n");
      out.write("                        <li><strong>UserServlet</strong>: ì¬ì©ì ê´ë ¨ ëª¨ë  ìì²­ ì²ë¦¬ (ë¡ê·¸ì¸, íìê°ì, ë§ì´íì´ì§ ë±)</li>\r\n");
      out.write("                        <li><strong>MovieServlet</strong>: ìí ê´ë ¨ ìì²­ ì²ë¦¬ (ëª©ë¡ ì¡°í, ìì¸ë³´ê¸°, ì¢ìì ë±)</li>\r\n");
      out.write("                        <li><strong>CinemaServlet</strong>: ìíê´ ì ë³´ AJAX ìì²­ ì²ë¦¬</li>\r\n");
      out.write("                        <li><strong>ScheduleServlet</strong>: ìì ì¼ì  AJAX ìì²­ ì²ë¦¬</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #27ae60;\">ð Model Layer (DAO)</h4>\r\n");
      out.write("                    <ul style=\"margin: 10px 0; padding-left: 20px;\">\r\n");
      out.write("                        <li><strong>UserListDAO</strong>: ì¬ì©ì ë°ì´í° CRUD ìì</li>\r\n");
      out.write("                        <li><strong>MovieListDAO</strong>: ìí ë°ì´í° ì¡°í ë° ì¢ìì ê¸°ë¥</li>\r\n");
      out.write("                        <li><strong>CinemaListDAO</strong>: ìíê´ ì ë³´ ì¡°í</li>\r\n");
      out.write("                        <li><strong>ScheduleListDAO</strong>: ìì ì¼ì  ê´ë¦¬</li>\r\n");
      out.write("                        <li><strong>ReserveListDAO</strong>: ìë§¤ ì ë³´ ê´ë¦¬</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 20px; font-size: 14px; margin-top: 15px;\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #f39c12;\">ð·ï¸ Value Object Layer</h4>\r\n");
      out.write("                    <ul style=\"margin: 10px 0; padding-left: 20px;\">\r\n");
      out.write("                        <li><strong>UserListVO</strong>: ì¬ì©ì ì ë³´ ë°ì´í° êµ¬ì¡°</li>\r\n");
      out.write("                        <li><strong>MovieListVO</strong>: ìí ì ë³´ ë°ì´í° êµ¬ì¡°</li>\r\n");
      out.write("                        <li><strong>CinemaListVO</strong>: ìíê´ ì ë³´ ë°ì´í° êµ¬ì¡°</li>\r\n");
      out.write("                        <li><strong>ScheduleListVO</strong>: ìì ì¼ì  ë°ì´í° êµ¬ì¡°</li>\r\n");
      out.write("                        <li><strong>ReserveListVO</strong>: ìë§¤ ì ë³´ ë°ì´í° êµ¬ì¡°</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4 style=\"color: #9b59b6;\">ð ê´ê³ ì¤ëª</h4>\r\n");
      out.write("                    <ul style=\"margin: 10px 0; padding-left: 20px;\">\r\n");
      out.write("                        <li><strong>Dependency (ì ì  íì´í)</strong>: Servletì´ DAOì VOë¥¼ ì¬ì©</li>\r\n");
      out.write("                        <li><strong>Association (ì¤ì  íì´í)</strong>: DAOê° VO ê°ì²´ë¥¼ ìì±/ë°í</li>\r\n");
      out.write("                        <li><strong>MVC í¨í´</strong>: Controller â Model â Database êµ¬ì¡°</li>\r\n");
      out.write("                        <li><strong>Front Controller</strong>: íëì ìë¸ë¦¿ì´ ì¬ë¬ ìì²­ ì²ë¦¬</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 20px; padding: 15px; background: #d5f4e6; border-radius: 8px; border-left: 5px solid #27ae60;\">\r\n");
      out.write("            <h4 style=\"color: #27ae60; margin-top: 0;\">ð¡ í´ëì¤ ë¤ì´ì´ê·¸ë¨ ìì± ê°ì´ë</h4>\r\n");
      out.write("            <p style=\"margin: 10px 0; font-size: 14px; line-height: 1.6;\">\r\n");
      out.write("                <strong>1. ëêµ¬ ì í:</strong> StarUML, PlantUML, Draw.io, Lucidchart ë±ì UML ëêµ¬ ì¬ì©<br>\r\n");
      out.write("                <strong>2. ë ì´ì´ë³ ë¶ë¥:</strong> Controller, Model(DAO), VO ë ì´ì´ë¡ ëªíí êµ¬ë¶<br>\r\n");
      out.write("                <strong>3. ê´ê³ íí:</strong> ìì¡´ì±(ì ì ), ì°ê´ì±(ì¤ì ), ìì(ì¼ê°í) íì´íë¡ êµ¬ë¶<br>\r\n");
      out.write("                <strong>4. ê°ëì±:</strong> í´ëì¤ëª, ìì±, ë©ìëë¥¼ ëªííê² íê¸°íê³  ììì¼ë¡ êµ¬ë¶<br>\r\n");
      out.write("                <strong>5. ë¬¸ìí:</strong> ê° í´ëì¤ì ì­í ê³¼ ê´ê³ë¥¼ ì¤ëªíë ë²ë¡ í¬í¨\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 20px; padding: 15px; background: #fff3cd; border-radius: 8px; border-left: 5px solid #f39c12;\">\r\n");
      out.write("            <h4 style=\"color: #f39c12; margin-top: 0;\">ð ï¸ ì¤ì  ìì± ë°©ë²</h4>\r\n");
      out.write("            <div style=\"font-size: 14px; line-height: 1.6;\">\r\n");
      out.write("                <p><strong>ë°©ë² 1: PlantUML ì½ë ìì±</strong></p>\r\n");
      out.write("                <pre style=\"background: #f8f9fa; padding: 10px; border-radius: 5px; overflow-x: auto; font-size: 12px;\">@startuml\r\n");
      out.write("!theme plain\r\n");
      out.write("skinparam backgroundColor #f8f9fa\r\n");
      out.write("skinparam class {\r\n");
      out.write("    BackgroundColor&lt;&lt;Controller&gt;&gt; #ffebee\r\n");
      out.write("    BackgroundColor&lt;&lt;DAO&gt;&gt; #e8f5e8\r\n");
      out.write("    BackgroundColor&lt;&lt;VO&gt;&gt; #fff3e0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("package \"Controller Layer\" {\r\n");
      out.write("    class UserServlet &lt;&lt;Controller&gt;&gt; {\r\n");
      out.write("        - udao: UserListDAO\r\n");
      out.write("        - mdao: MovieListDAO\r\n");
      out.write("        + service(req, resp): void\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    class MovieServlet &lt;&lt;Controller&gt;&gt; {\r\n");
      out.write("        - mdao: MovieListDAO\r\n");
      out.write("        + service(req, resp): void\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("package \"Model Layer\" {\r\n");
      out.write("    class UserListDAO &lt;&lt;DAO&gt;&gt; {\r\n");
      out.write("        + login(id, pw): UserListVO\r\n");
      out.write("        + register(user): boolean\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    class MovieListDAO &lt;&lt;DAO&gt;&gt; {\r\n");
      out.write("        + getMovieList(): List&lt;MovieListVO&gt;\r\n");
      out.write("        + getTopMovies(): List&lt;MovieListVO&gt;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("package \"Value Object Layer\" {\r\n");
      out.write("    class UserListVO &lt;&lt;VO&gt;&gt; {\r\n");
      out.write("        - userNo: int\r\n");
      out.write("        - userId: String\r\n");
      out.write("        - userName: String\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    class MovieListVO &lt;&lt;VO&gt;&gt; {\r\n");
      out.write("        - movieId: int\r\n");
      out.write("        - movieTitle: String\r\n");
      out.write("        - moviePrice: int\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("UserServlet ..&gt; UserListDAO : uses\r\n");
      out.write("UserServlet ..&gt; UserListVO : uses\r\n");
      out.write("MovieServlet ..&gt; MovieListDAO : uses\r\n");
      out.write("UserListDAO --&gt; UserListVO : creates\r\n");
      out.write("MovieListDAO --&gt; MovieListVO : creates\r\n");
      out.write("\r\n");
      out.write("@enduml</pre>\r\n");
      out.write("                \r\n");
      out.write("                <p style=\"margin-top: 15px;\"><strong>ë°©ë² 2: ì¨ë¼ì¸ ëêµ¬ íì©</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px;\">\r\n");
      out.write("                    <li><strong>Draw.io</strong>: ë¬´ë£, ì¹ ê¸°ë°, ì§ê´ì ì¸ ì¸í°íì´ì¤</li>\r\n");
      out.write("                    <li><strong>Lucidchart</strong>: íì ê¸°ë¥, ííë¦¿ ì ê³µ</li>\r\n");
      out.write("                    <li><strong>StarUML</strong>: ì ë¬¸ UML ëêµ¬, ë¤ìí ë¤ì´ì´ê·¸ë¨ ì§ì</li>\r\n");
      out.write("                    <li><strong>Visual Paradigm</strong>: ì½ë ì­ê³µí ê¸°ë¥</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("                <p style=\"margin-top: 15px;\"><strong>ë°©ë² 3: IDE íë¬ê·¸ì¸ ì¬ì©</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px;\">\r\n");
      out.write("                    <li><strong>Eclipse UML Generator</strong>: ìì¤ì½ëìì ìë ìì±</li>\r\n");
      out.write("                    <li><strong>IntelliJ IDEA Ultimate</strong>: UML ë¤ì´ì´ê·¸ë¨ ì§ì</li>\r\n");
      out.write("                    <li><strong>VS Code Extensions</strong>: PlantUML ë¯¸ë¦¬ë³´ê¸°</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 20px; padding: 15px; background: #e1f5fe; border-radius: 8px; border-left: 5px solid #03a9f4;\">\r\n");
      out.write("            <h4 style=\"color: #0277bd; margin-top: 0;\">ð ë¨ê³ë³ ìì± ê°ì´ë</h4>\r\n");
      out.write("            <div style=\"font-size: 14px; line-height: 1.6;\">\r\n");
      out.write("                <p><strong>1ë¨ê³: í´ëì¤ ìë³</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px; margin: 5px 0;\">\r\n");
      out.write("                    <li>íë¡ì í¸ì ëª¨ë  .java íì¼ ëª©ë¡ ìì±</li>\r\n");
      out.write("                    <li>Servlet, DAO, VOë¡ ë¶ë¥</li>\r\n");
      out.write("                    <li>ê° í´ëì¤ì ì£¼ì ìì±ê³¼ ë©ìë íì</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("                <p><strong>2ë¨ê³: ê´ê³ ë¶ì</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px; margin: 5px 0;\">\r\n");
      out.write("                    <li>Servletì´ ì¬ì©íë DAO í´ëì¤ íì¸</li>\r\n");
      out.write("                    <li>DAOê° ë°ííë VO í´ëì¤ íì¸</li>\r\n");
      out.write("                    <li>ìì¡´ì±, ì°ê´ì±, ìì ê´ê³ êµ¬ë¶</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("                <p><strong>3ë¨ê³: ë ì´ìì ì¤ê³</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px; margin: 5px 0;\">\r\n");
      out.write("                    <li>Controller â Model â VO ììë¡ ìí ë°°ì¹</li>\r\n");
      out.write("                    <li>ê´ë ¨ í´ëì¤ë¤ì ê·¸ë£¹í</li>\r\n");
      out.write("                    <li>ê´ê³ì ì´ êµì°¨íì§ ìëë¡ ë°°ì¹</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("                <p><strong>4ë¨ê³: ìì¸ ìì±</strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px; margin: 5px 0;\">\r\n");
      out.write("                    <li>í´ëì¤ëª, ìì±, ë©ìë ìì¸ ê¸°ì</li>\r\n");
      out.write("                    <li>ì ê·¼ ì íì íì (+public, -private, #protected)</li>\r\n");
      out.write("                    <li>ë°ì´í° íì ëªì</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("                <p><strong>5ë¨ê³: ìµì¢ ê²í </strong></p>\r\n");
      out.write("                <ul style=\"padding-left: 20px; margin: 5px 0;\">\r\n");
      out.write("                    <li>ëª¨ë  í´ëì¤ê° í¬í¨ëìëì§ íì¸</li>\r\n");
      out.write("                    <li>ê´ê³ì ì ë°©í¥ê³¼ ì¢ë¥ê° ì¬ë°ë¥¸ì§ ì ê²</li>\r\n");
      out.write("                    <li>ë²ë¡ì ì¤ëª ì¶ê°</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
